On branch dev-joey
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   api/pom.xml
	modified:   api/src/main/java/org/opencord/dhcpl2relay/DhcpAllocationInfo.java
	modified:   api/src/main/java/org/opencord/dhcpl2relay/DhcpL2RelayEvent.java
	modified:   api/src/main/java/org/opencord/dhcpl2relay/DhcpL2RelayListener.java
	modified:   api/src/main/java/org/opencord/dhcpl2relay/DhcpL2RelayService.java
	modified:   api/src/main/java/org/opencord/dhcpl2relay/DhcpL2RelayStoreDelegate.java
	modified:   api/src/main/java/org/opencord/dhcpl2relay/package-info.java
	modified:   app/app.xml
	modified:   app/features.xml
	modified:   app/pom.xml
	modified:   app/src/main/java/org/opencord/dhcpl2relay/cli/DhcpL2RelayAllocationsCommand.java
	modified:   app/src/main/java/org/opencord/dhcpl2relay/cli/DhcpL2RelayClearAllocationsCommand.java
	modified:   app/src/main/java/org/opencord/dhcpl2relay/cli/DhcpL2RelayRemoveAllocationsCommand.java
	modified:   app/src/main/java/org/opencord/dhcpl2relay/cli/DhcpL2RelayStatsCommand.java
	modified:   app/src/main/java/org/opencord/dhcpl2relay/cli/package-info.java
	modified:   app/src/main/java/org/opencord/dhcpl2relay/impl/DhcpL2Relay.java
	modified:   app/src/main/java/org/opencord/dhcpl2relay/impl/DhcpL2RelayConfig.java
	modified:   app/src/main/java/org/opencord/dhcpl2relay/impl/DhcpL2RelayCounterNames.java
	modified:   app/src/main/java/org/opencord/dhcpl2relay/impl/DhcpL2RelayCountersIdentifier.java
	modified:   app/src/main/java/org/opencord/dhcpl2relay/impl/DhcpL2RelayCountersStore.java
	modified:   app/src/main/java/org/opencord/dhcpl2relay/impl/DhcpL2RelayStatistics.java
	modified:   app/src/main/java/org/opencord/dhcpl2relay/impl/OsgiPropertyConstants.java
	modified:   app/src/main/java/org/opencord/dhcpl2relay/impl/SimpleDhcpL2RelayCountersStore.java
	modified:   app/src/main/java/org/opencord/dhcpl2relay/impl/package-info.java
	modified:   app/src/main/java/org/opencord/dhcpl2relay/impl/packet/DhcpOption82Data.java
	modified:   app/src/main/java/org/opencord/dhcpl2relay/impl/packet/package-info.java
	modified:   app/src/main/java/org/opencord/dhcpl2relay/rest/DhcpL2RelayWebResource.java
	modified:   app/src/main/java/org/opencord/dhcpl2relay/rest/package-info.java
	modified:   app/src/main/webapp/WEB-INF/web.xml
	modified:   app/src/test/java/org/opencord/dhcpl2relay/impl/DhcpL2RelayConfigTest.java
	modified:   app/src/test/java/org/opencord/dhcpl2relay/impl/DhcpL2RelayCountersStoreTest.java
	modified:   app/src/test/java/org/opencord/dhcpl2relay/impl/DhcpL2RelayTest.java
	modified:   app/src/test/java/org/opencord/dhcpl2relay/impl/DhcpL2RelayTestBase.java
	modified:   pom.xml
	modified:   spotbugs-security-exclude.xml
	modified:   spotbugs-security-include.xml

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	msg

no changes added to commit (use "git add" and/or "git commit -a")
